# Generated by Django 2.0.8 on 2018-08-30 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pledge',
            old_name='wishList',
            new_name='wish_list',
        ),
        migrations.RenameField(
            model_name='wishlistitem',
            old_name='wishList',
            new_name='wish_list',
        ),
    ]
