# Generated by Django 2.0.8 on 2018-10-05 23:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0003_remove_wishlistitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledge',
            name='pledged_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
