# Generated by Django 2.0.8 on 2018-10-09 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0005_auto_20181005_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pledge',
            name='pledged_at',
        ),
    ]
