# Generated by Django 2.0.8 on 2018-10-09 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0006_remove_pledge_pledged_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pledge',
            name='owner',
        ),
    ]
